[services.redis]
image = "redis:alpine"
container_name = "redis"
user = "root"
command = "redis-server /etc/redis.conf"
restart = "unless-stopped"
volumes = ["/docker/redis/redis.conf:/etc/redis.conf", "redis_temp:/tmp/redis"]

[services.redis_temp]
image = "busybox"
container_name = "redis_temp"
command = "chmod -R 777 /tmp/redis"
volumes = ["redis_temp:/tmp/redis"]

[volumes.redis_temp]
external = true
