version: "3"
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    environment:
      - TZ=Europe/Helsinki
    volumes:
      - /docker/homeautomation/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - home-assistant
      - mariadb
      - proxy
    ports:
      - "8123:8123"
    depends_on:
      - deconz
      - mosquitto
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.home-assistant-redirect.entrypoints=http"
      - "traefik.http.routers.home-assistant-redirect.rule=Host(`home.reekynet.com`)"
      - "traefik.http.middlewares.http2https.redirectscheme.scheme=https"
      - "traefik.http.routers.home-assistant-redirect.middlewares=http2https"

      - "traefik.http.routers.home-assistant.entrypoints=https"
      - "traefik.http.routers.home-assistant.rule=Host(`home.reekynet.com`)"
      - "traefik.http.routers.home-assistant.tls=true"
      - "traefik.http.routers.home-assistant.tls.certresolver=http"
      - "traefik.http.routers.home-assistant.service=home-assistant"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"

  deconz:
    container_name: deconz
    image: marthoc/deconz
    environment:
      - TZ=Europe/Helsinki
      - DECONZ_WEB_PORT=8083
      - DECONZ_WS_PORT=8084
      - DECONZ_UPNP=0
      - DECONZ_VNC_PORT=5901
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=${DECONZ_VNC_PASSWORD}
      - DEBUG_OTAU=1
    network_mode: host
    volumes:
      - /docker/homeautomation/deconz/deconz:/root/.local/share/dresden-elektronik/deCONZ
      - /docker/homeautomation/deconz/otau:/root/otau
      - /etc/localtime:/etc/localtime:ro
    restart: always
    devices:
      - /dev/ttyACM0

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    environment:
      - TZ=Europe/Helsinki
    ports:
      - "1883:1883"
    networks:
      - home-assistant
    volumes:
      - /docker/homeautomation/mosquitto:/mosquitto
      - /etc/localtime:/etc/localtime:ro
    restart: always

  node-red:
    container_name: node-red
    image: nodered/node-red
    environment:
      - TZ=Europe/Helsinki
    networks:
      - home-assistant
      - proxy
    ports:
      - "1880:1880"
    volumes:
      - /docker/homeautomation/node-red:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - home-assistant
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.node-red-redirect.entrypoints=http"
      - "traefik.http.routers.node-red-redirect.rule=Host(`node.reekynet.com`)"
      - "traefik.http.middlewares.http2https.redirectscheme.scheme=https"
      - "traefik.http.routers.node-red-redirect.middlewares=http2https"

      - "traefik.http.routers.node-red.entrypoints=https"
      - "traefik.http.routers.node-red.rule=Host(`node.reekynet.com`)"
      - "traefik.http.routers.node-red.tls=true"
      - "traefik.http.routers.node-red.tls.certresolver=http"
      - "traefik.http.routers.node-red.service=node-red"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.node-red.loadbalancer.server.port=1880"

networks:
  home-assistant:
    external: false
  mariadb:
    external: true
  proxy:
    external: true
