require 'pluginmanager'
require 'autocmd'
require 'keybinds'
require 'settings'
require 'common'

-- Plugin configurations
require 'pluginconf.lualine'
require 'pluginconf.bufferline'
require 'pluginconf.lsp'
require 'pluginconf.completion'
require 'pluginconf.treesitter'
require 'pluginconf.indent-blankline'
require 'pluginconf.nvim-tree'
require 'pluginconf.colorscheme'
