volumes:
  data: {}
services:
  postgres:
    container_name: postgres
    image: postgres:18
    networks:
      - postgres
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/var/lib/postgresql
    restart: unless-stopped
networks:
  postgres:
    external: true
