volumes:
  data: {}
services:
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/var/lib/postgresql/data
    restart: unless-stopped
networks:
  postgres:
    external: true
