version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/portainer:/data
      - /etc/localtime:/etc/localtime:ro
