#! /bin/sh

# set screen timeout
xset s 300 120
xset dpms 422

# screen locker
xss-lock -n ~/Scripts/dim-screen.sh -- evenbetterlockscreen -l &

# lock screen
evenbetterlockscreen -l &

# set wallpaper
wal -R

# Start hotkey daemon
sxhkd &

bspc monitor -d web term chat mail music 6 7 

bspc config border_width         0 
bspc config window_gap           37 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Franz desktop=^3
bspc rule -a Thunderbird desktop=^4

bspc rule -a Zathura state=tiled
bspc rule -a Nightly:Navigator state=tiled
bspc rule -a kdeconnect-indicator state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true

# set pywal colors
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"


# set cursor style
xsetroot -cursor_name left_ptr
 
# startup applications
joplin-desktop &
compton -f --config ~/.config/compton/config &
redshift &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
telegram-desktop &
setxkbmap eu &
/usr/lib/kdeconnectd &
kdeconnect-indicator &
udiskie --tray &
xfce4-clipman &
/usr/bin/gnome-keyring-daemon --start --components=secrets &
~/Scripts/polybar.sh &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
blueberry-tray &
nm-applet &
thunderbird &
mpDris2 &

# hide mouse cursor
unclutter -idle 1 &
