[actions]
dconf_load = "dconf load / < ~/.config/dconf.ini"
kanagawa_compile = "nvim +KanagawaCompile +qa"
scripts_chmod = "chmod +x ~/.scripts/*"

[config]
backup = true
banner = true
create = true
dotpath = "home"
ignoreempty = false
keepdot = true
link_dotfile_default = "nolink"
link_on_import = "nolink"
longkey = false
showdiff = false
workdir = "~/.config/dotdrop"

[dotfiles.d_scripts]
dst = "~/.scripts"
src = ".scripts"
actions = ["scripts_chmod"]

[dotfiles.d_mpv]
dst = "~/.config/mpv"
src = ".config/mpv"

[dotfiles.d_nvim]
dst = "~/.config/nvim"
src = ".config/nvim"
actions = ["kanagawa_compile"]
instignore = ["*-lock.json"]

[dotfiles."f_abcde.conf"]
dst = "~/.abcde.conf"
src = ".abcde.conf"

[dotfiles.d_ssh]
dst = "~/.ssh"
src = ".ssh"

[dotfiles.f_beets_config]
dst = "~/.config/beets/config.yaml"
src = ".config/beets/config.yaml"

[dotfiles.f_beets_whitelist]
dst = "~/.config/beets/whitelist"
src = ".config/beets/whitelist"

[dotfiles.f_gitconfig]
dst = "~/.config/git/config"
src = ".config/git/config"

[dotfiles."f_makepkg.conf"]
dst = "~/.config/pacman/makepkg.conf"
src = ".config/pacman/makepkg.conf"

[dotfiles."f_ssh.conf"]
dst = "~/.ssh/config"
src = ".ssh/config"

[dotfiles.f_zprofile]
dst = "~/.zprofile"
src = ".zprofile"

[dotfiles.f_zshrc]
dst = "~/.zshrc"
src = ".zshrc"

[dotfiles.d_zsh]
src = ".config/zsh"
dst = "~/.config/zsh"

[dotfiles."f_fonts.conf"]
src = ".config/fontconfig/fonts.conf"
dst = "~/.config/fontconfig/fonts.conf"

[dotfiles.f_ignore]
src = ".ignore"
dst = "~/.ignore"

[dotfiles.f_hushlogin]
src = ".hushlogin"
dst = "~/.hushlogin"

[dotfiles."f_paru.conf"]
src = ".config/paru/paru.conf"
dst = "~/.config/paru/paru.conf"

[dotfiles."f_gpg-agent.conf"]
src = ".gnupg/gpg-agent.conf"
dst = "~/.gnupg/gpg-agent.conf"
chmod = "600"

[dotfiles."f_gpg.conf"]
src = ".gnupg/gpg.conf"
dst = "~/.gnupg/gpg.conf"

[dotfiles."f_gpg_scdaemon.conf"]
src = ".gnupg/scdaemon.conf"
dst = "~/.gnupg/scdaemon.conf"

[dotfiles."f_electron-flags.conf"]
src = ".config/electron-flags.conf"
dst = "~/.config/electron-flags.conf"

[dotfiles."f_electron12-flags.conf"]
src = ".config/electron12-flags.conf"
dst = "~/.config/electron12-flags.conf"

[dotfiles.f_pam_environment]
src = ".pam_environment"
dst = "~/.pam_environment"

[dotfiles."f_dconf.ini"]
src = ".config/dconf.ini"
dst = "~/.config/dconf.ini"
actions = ["dconf_load"]

[dotfiles."f_docker-config.json"]
src = ".docker/config.json"
dst = "~/.docker/config.json"
chmod = "600"

[dotfiles.f_npmrc]
src = ".npmrc"
dst = "~/.npmrc"
chmod = "600"

[dotfiles.f_zellij]
src = ".config/zellij/config.kdl"
dst = "~/.config/zellij/config.kdl"

[dotfiles.f_tmux]
src = ".config/tmux/tmux.conf"
dst = "~/.config/tmux/tmux.conf"

[dotfiles.f_neovide_config]
src = ".config/neovide/config.toml"
dst = "~/.config/neovide/config.toml"

[dotfiles.f_lazygit.yml]
src = ".config/jesseduffield/lazygit/config.yml"
dst = "~/.config/jesseduffield/lazygit/config.yml"

[dotfiles.f_lazydocker.yml]
src = ".config/jesseduffield/lazydocker/config.yml"
dst = "~/.config/jesseduffield/lazydocker/config.yml"

[profiles.pacman]
dotfiles = ["f_makepkg.conf", "f_paru.conf"]

[profiles.terminal]
dotfiles = [
  "d_scripts",
  "f_lazygit.yml",
  "f_lazydocker.yml",
  "f_neovide_config",
  "d_nvim",
  "d_ssh",
  "d_zsh",
  "f_gitconfig",
  "f_hushlogin",
  "f_ignore",
  "f_zellij",
  "f_tmux",
  "f_zshrc",
  "f_npmrc",
]

[profiles.media]
dotfiles = ["d_mpv", "f_abcde.conf", "f_beets_config", "f_beets_whitelist"]

[profiles.gpg]
dotfiles = [
  "f_gpg-agent.conf",
  "f_gpg.conf",
  "f_gpg_scdaemon.conf",
  "f_pam_environment",
]

[profiles.Mirkwood]
include = ["pacman", "terminal", "media", "gpg"]
dotfiles = ["f_dconf.ini", "f_docker-config.json", "f_fonts.conf"]

[profiles.Mirkwood.variables]
wayland = true

[profiles.VentoyArch]
include = ["pacman", "terminal", "media", "gpg"]
dotfiles = ["f_dconf.ini", "f_fonts.conf"]

[profiles.VentoyArch.variables]
wayland = true

[profiles.Shire]
include = ["pacman", "terminal", "media", "gpg"]
dotfiles = ["f_dconf.ini", "f_fonts.conf"]

[profiles.Shire.variables]
wayland = true

[profiles.Moria]
include = ["pacman", "terminal", "media", "gpg"]
dotfiles = ["f_dconf.ini", "f_zprofile", "f_fonts.conf"]

[profiles.Moria.variables]
wayland = true

[profiles.Tirion]
include = ["terminal", "gpg"]

[profiles.Gondor]
include = ["pacman", "terminal"]

[profiles.Orthanc]
include = ["terminal", "gpg"]
dotfiles = ["f_dconf.ini"]

[profiles.Orthanc.variables]
wayland = false

[profiles.Isengard]
include = ["terminal"]

[profiles.Isengard.variables]
distro_id = "termux"

[profiles.Edoras]
include = ["terminal"]

[profiles.localhost]
include = ["terminal"]

[profiles.ViiruJaTeippi]
include = ["terminal"]

[profiles.Evendim]
include = ["terminal", "pacman"]
