[config]
backup = true
banner = true
create = true
dotpath = "root"
ignoreempty = false
keepdot = true
link_dotfile_default = "nolink"
link_on_import = "nolink"
longkey = false
showdiff = false
workdir = "~/.config/sdotdrop"

[dotfiles."f_60-uinput-permissions.rules"]
dst = "/etc/udev/rules.d/60-uinput-permissions.rules"
src = "etc/udev/rules.d/60-uinput-permissions.rules"

[dotfiles."f_yubikey_udev.rules"]
dst = "/etc/udev/rules.d/20-yubikey.rules"
src = "etc/udev/rules.d/20-yubikey.rules"

[dotfiles.d_bin]
dst = "/usr/local/bin"
src = "usr/local/bin"

[dotfiles.d_network]
src = "etc/systemd/network"
dst = "/etc/systemd/network"

[dotfiles."f_networkd.conf"]
src = "etc/systemd/networkd.conf"
dst = "/etc/systemd/networkd.conf"

[dotfiles."f_99-sysctl.conf"]
dst = "/etc/sysctl.d/99-sysctl.conf"
src = "etc/sysctl.d/99-sysctl.conf"

[dotfiles."f_adb.service"]
dst = "/etc/systemd/system/adb.service"
src = "etc/systemd/system/adb.service"

[dotfiles."f_clamd.conf"]
dst = "/etc/clamav/clamd.conf"
src = "etc/clamav/clamd.conf"

[dotfiles.f_cryptissue]
dst = "/etc/cryptissue"
src = "etc/cryptissue"

[dotfiles."f_detected.sh"]
dst = "/etc/clamav/detected.sh"
src = "etc/clamav/detected.sh"

[dotfiles."f_freetype2.sh"]
dst = "/etc/profile.d/freetype2.sh"
src = "etc/profile.d/freetype2.sh"

[dotfiles."f_fonts.conf"]
dst = "/etc/fonts/local.conf"
src = "etc/fonts/local.conf"

[dotfiles."f_locale.conf"]
dst = "/etc/locale.conf"
src = "etc/locale.conf"

[dotfiles."f_locale.gen"]
dst = "/etc/locale.gen"
src = "etc/locale.gen"

[dotfiles."f_logind.conf"]
dst = "/etc/systemd/logind.conf"
src = "etc/systemd/logind.conf"

[dotfiles."f_bluetooth.conf"]
dst = "/etc/bluetooth/main.conf"
src = "etc/bluetooth/main.conf"

[dotfiles."f_pacman.conf"]
dst = "/etc/pacman.conf"
src = "etc/pacman.conf"

[dotfiles.f_pacman_zsh_hook]
dst = "/etc/pacman.d/hooks/zsh.hook"
src = "etc/pacman.d/hooks/zsh.hook"

[dotfiles."f_plymouthd.conf"]
src = "etc/plymouth/plymouthd.conf"
dst = "/etc/plymouth/plymouthd.conf"

[dotfiles.f_sshd_config]
dst = "/etc/ssh/sshd_config"
src = "etc/ssh/sshd_config"

[dotfiles."f_welcomemessage.conf"]
dst = "/etc/welcomemessage.conf"
src = "etc/welcomemessage.conf"

[dotfiles."f_99-conbee-usb-serial.rules"]
src = "etc/udev/rules.d/99-conbee-usb-serial.rules"
dst = "/etc/udev/rules.d/99-conbee-usb-serial.rules"

[dotfiles."f_99-lowbat.rules"]
src = "etc/udev/rules.d/99-lowbat.rules"
dst = "/etc/udev/rules.d/99-lowbat.rules"

[dotfiles."f_sleep.conf"]
src = "etc/systemd/sleep.conf"
dst = "/etc/systemd/sleep.conf"

[dotfiles.f_fstab]
src = "etc/fstab"
dst = "/etc/fstab"

[dotfiles.f_ignore]
src = ".ignore"
dst = "/.ignore"

[dotfiles."f_mkinitcpio.conf"]
src = "etc/mkinitcpio.conf"
dst = "/etc/mkinitcpio.conf"

[dotfiles."f_vconsole.conf"]
src = "etc/vconsole.conf"
dst = "/etc/vconsole.conf"

[dotfiles."f_20-quiet-printk.conf"]
src = "etc/sysctl.d/20-quiet-printk.conf"
dst = "/etc/sysctl.d/20-quiet-printk.conf"

[dotfiles."f_system.conf"]
src = "etc/systemd/system.conf"
dst = "/etc/systemd/system.conf"

[dotfiles.f_cpupower]
src = "etc/default/cpupower"
dst = "/etc/default/cpupower"

[dotfiles."f_pacserve.service.conf"]
src = "etc/pacserve/pacserve.service.conf"
dst = "/etc/pacserve/pacserve.service.conf"

[dotfiles."f_mkinitcpio_linux.preset"]
src = "etc/mkinitcpio.d/linux.preset"
dst = "/etc/mkinitcpio.d/linux.preset"

[dotfiles."f_mkinitcpio_linux-lts.preset"]
src = "etc/mkinitcpio.d/linux-lts.preset"
dst = "/etc/mkinitcpio.d/linux-lts.preset"

[dotfiles.f_cmdline]
src = "etc/kernel/cmdline"
dst = "/etc/kernel/cmdline"

[dotfiles."f_timesyncd.conf"]
src = "etc/systemd/timesyncd.conf"
dst = "/etc/systemd/timesyncd.conf"

[dotfiles.f_sudoers_pacman]
src = "etc/sudoers.d/pacman"
dst = "/etc/sudoers.d/pacman"

[dotfiles."f_doas.conf"]
src = "etc/doas.conf"
dst = "/etc/doas.conf"

[profiles.Network]
dotfiles = ["d_network", "f_networkd.conf"]

[profiles.Locale]
dotfiles = ["f_locale.conf", "f_locale.gen"]

[profiles.Pacman]
dotfiles = [
  "f_pacman.conf",
  "f_pacman_zsh_hook",
  "f_pacserve.service.conf",
  "f_sudoers_pacman",
]

[profiles.Mirkwood]
dotfiles = [
  "d_bin",
  "f_20-quiet-printk.conf",
  "f_60-uinput-permissions.rules",
  "f_99-lowbat.rules",
  "f_adb.service",
  "f_bluetooth.conf",
  "f_cmdline",
  "f_cpupower",
  "f_cryptissue",
  "f_doas.conf",
  "f_fonts.conf",
  "f_freetype2.sh",
  "f_ignore",
  "f_logind.conf",
  "f_mkinitcpio.conf",
  "f_mkinitcpio_linux.preset",
  "f_mkinitcpio_linux-lts.preset",
  "f_plymouthd.conf",
  "f_sshd_config",
  "f_system.conf",
  "f_timesyncd.conf",
  "f_welcomemessage.conf",
]
include = ["Locale", "Pacman", "Network"]

[profiles.Moria]
include = ["Locale", "Pacman", "Network"]
dotfiles = [
  "f_99-sysctl.conf",
  "f_cmdline",
  "f_cpupower",
  "f_doas.conf",
  "f_mkinitcpio.conf",
  "f_mkinitcpio_linux.preset",
  "f_mkinitcpio_linux-lts.preset",
  "f_plymouthd.conf",
  "f_sshd_config",
]

[profiles.Gondor]
include = ["Locale", "Pacman"]
dotfiles = ["f_doas.conf", "f_sshd_config"]

[profiles.localhost]
include = ["Locale"]

[profiles.Edoras]
include = ["Pacman"]

[profiles.mko-laptop]
dotfiles = ["f_cpupower", "f_yubikey_udev.rules", "f_doas.conf"]
