[actions]
nvim-packer-sync = "nvim +PackerSync"

[config]
backup = true
banner = true
create = true
dotpath = "home"
ignoreempty = false
keepdot = true
link_dotfile_default = "nolink"
link_on_import = "nolink"
longkey = false
showdiff = false
workdir = "~/.config/dotdrop"

[dotfiles]

[dotfiles.d_systemd]
dst = "~/.config/systemd/user"
src = ".config/systemd/user"

[dotfiles.d_mpv]
dst = "~/.config/mpv"
src = ".config/mpv"

[dotfiles.d_neomutt]
dst = "~/.config/neomutt"
src = ".config/neomutt"

[dotfiles.d_imapnotify]
dst = "~/.config/imapnotify"
src = ".config/imapnotify"

[dotfiles.f_nvim_init]
dst = "~/.config/nvim/init.lua"
src = ".config/nvim/init.lua"

[dotfiles.d_nvim_lua]
actions = ["nvim-packer-sync"]
dst = "~/.config/nvim/lua"
src = ".config/nvim/lua"

[dotfiles.d_nvim_ftplugin]
dst = "~/.config/nvim/ftplugin"
src = ".config/nvim/ftplugin"

[dotfiles.d_sway]
dst = "~/.config/sway"
src = ".config/sway"

[dotfiles.d_waybar]
dst = "~/.config/waybar"
src = ".config/waybar"

[dotfiles.d_wofi]
src = ".config/wofi"
dst = "~/.config/wofi"

[dotfiles."f_abcde.conf"]
dst = "~/.abcde.conf"
src = ".abcde.conf"

[dotfiles.f_mbsyncrc]
dst = "~/.mbsyncrc"
src = ".mbsyncrc"

[dotfiles."f_alacritty.yml"]
dst = "~/.config/alacritty/alacritty.yml"
src = ".config/alacritty/alacritty.yml"

[dotfiles.f_authorized_keys]
dst = "~/.ssh/authorized_keys"
src = ".ssh/authorized_keys"

[dotfiles.f_beets_config]
dst = "~/.config/beets/config.yaml"
src = ".config/beets/config.yaml"

[dotfiles.f_beets_whitelist]
dst = "~/.config/beets/whitelist"
src = ".config/beets/whitelist"

[dotfiles.f_bspwmrc]
dst = "~/.config/bspwm/bspwmrc"
src = ".config/bspwm/bspwmrc"

[dotfiles.f_gitconfig]
dst = "~/.gitconfig"
src = ".gitconfig"

[dotfiles.f_libra_config]
dst = "~/.config/libra/config.toml"
src = ".config/libra/config.toml"

[dotfiles.f_mailcap]
dst = "~/.mailcap"
src = ".mailcap"

[dotfiles."f_makepkg.conf"]
dst = "~/.config/pacman/makepkg.conf"
src = ".config/pacman/makepkg.conf"

[dotfiles.f_mako_config]
dst = "~/.config/mako/config"
src = ".config/mako/config"

[dotfiles."f_mimeo_associations.txt"]
dst = "~/.config/mimeo/associations.txt"
src = ".config/mimeo/associations.txt"

[dotfiles."f_mpd.conf"]
dst = "~/.config/mpd/mpd.conf"
src = ".config/mpd/mpd.conf"

[dotfiles."f_mpdris2.conf"]
dst = "~/.config/mpDris2/mpDris2.conf"
src = ".config/mpDris2/mpDris2.conf"

[dotfiles."f_mpdscribble.conf"]
dst = "~/.mpdscribble/mpdscribble.conf"
src = ".mpdscribble/mpdscribble.conf"

[dotfiles.f_ncmpcpp_bindings]
dst = "~/.config/ncmpcpp/bindings"
src = ".config/ncmpcpp/bindings"

[dotfiles."f_ranger.conf"]
dst = "~/.config/ranger/rc.conf"
src = ".config/ranger/rc.conf"

[dotfiles."f_ranger_commands.py"]
dst = "~/.config/ranger/commands.py"
src = ".config/ranger/commands.py"

[dotfiles."f_redshift.conf"]
dst = "~/.config/redshift/redshift.conf"
src = ".config/redshift/redshift.conf"

[dotfiles."f_rtv.cfg"]
dst = "~/.config/rtv/rtv.cfg"
src = ".config/rtv/rtv.cfg"

[dotfiles."f_ssh.conf"]
dst = "~/.ssh/config"
src = ".ssh/config"

[dotfiles."f_steam-native.desktop"]
dst = "~/.local/share/applications/steam-native.desktop"
src = ".local/share/applications/steam-native.desktop"

[dotfiles."f_tdesktop_lang.strings"]
dst = "~/.config/telegram-desktop/lang.strings"
src = ".config/telegram-desktop/lang.strings"

[dotfiles."f_tmux.conf"]
dst = "~/.tmux.conf"
src = ".tmux.conf"

[dotfiles.f_youtube-dl_config]
dst = "~/.config/youtube-dl/config"
src = ".config/youtube-dl/config"

[dotfiles.d_zathura]
dst = "~/.config/zathura"
src = ".config/zathura"

[dotfiles.f_zprofile]
dst = "~/.zprofile"
src = ".zprofile"

[dotfiles.f_zshrc]
dst = "~/.zshrc"
src = ".zshrc"

[dotfiles.d_zsh]
src = ".config/zsh"
dst = "~/.config/zsh"

[dotfiles."f_fonts.conf"]
src = ".config/fontconfig/fonts.conf"
dst = "~/.config/fontconfig/fonts.conf"

[dotfiles.f_ripgrep_ignore]
src = ".ignore"
dst = "~/.ignore"

[dotfiles."f_ncmpcpp.conf"]
src = ".config/ncmpcpp/config"
dst = "~/.config/ncmpcpp/config"

[dotfiles.f_hushlogin]
src = ".hushlogin"
dst = "~/.hushlogin"

[dotfiles."f_paru.conf"]
src = ".config/paru/paru.conf"
dst = "~/.config/paru/paru.conf"

[dotfiles.f_msmtp_config]
src = ".config/msmtp/config"
dst = "~/.config/msmtp/config"

[dotfiles."f_foot.ini"]
src = ".config/foot/foot.ini"
dst = "~/.config/foot/foot.ini"

[dotfiles."f_gpg-agent.conf"]
src = ".gnupg/gpg-agent.conf"
dst = "~/.gnupg/gpg-agent.conf"
chmod = "600"

[dotfiles."f_gpg.conf"]
src = ".gnupg/gpg.conf"
dst = "~/.gnupg/gpg.conf"

[dotfiles."f_gpg_scdaemon.conf"]
src = ".gnupg/scdaemon.conf"
dst = "~/.gnupg/scdaemon.conf"

[dotfiles."f_electron-flags.conf"]
src = ".config/electron-flags.conf"
dst = "~/.config/electron-flags.conf"

[dotfiles."f_electron12-flags.conf"]
src = ".config/electron12-flags.conf"
dst = "~/.config/electron12-flags.conf"

[dotfiles.f_pam_environment]
src = ".pam_environment"
dst = "~/.pam_environment"

[profiles]

[profiles.base]
dotfiles = ["d_systemd"]

[profiles.terminal]
dotfiles = [
  "f_hushlogin",
  "f_ripgrep_ignore",
  "f_ranger_commands.py",
  "f_rtv.cfg",
  "f_mailcap",
  "d_zsh",
  "f_zshrc",
  "f_tmux.conf",
  "f_ranger.conf",
  "f_ssh.conf",
  "f_authorized_keys",
  "f_nvim_init",
  "d_nvim_lua",
  "d_nvim_ftplugin",
  "f_gitconfig",
  "f_alacritty.yml",
]

[profiles.email]
dotfiles = ["d_neomutt", "d_imapnotify", "f_mbsyncrc", "f_msmtp_config"]

[profiles.media]
dotfiles = [
  "f_beets_config",
  "f_beets_whitelist",
  "f_abcde.conf",
  "d_mpv",
  "f_youtube-dl_config",
  "f_mpd.conf",
  "f_ncmpcpp_bindings",
  "f_ncmpcpp.conf",
  "f_libra_config",
  "f_mpdscribble.conf",
  "f_mpdris2.conf",
]

[profiles.sway]
dotfiles = [
  "d_sway",
  "d_waybar",
  "d_wofi",
  "f_mako_config",
  "f_redshift.conf",
  "d_zathura",
  "f_mimeo_associations.txt",
  "f_tdesktop_lang.strings",
  "f_fonts.conf",
  "f_zprofile",
  "f_electron-flags.conf",
  "f_electron12-flags.conf",
]

[profiles.pacman]
dotfiles = ["f_makepkg.conf", "f_paru.conf"]

[profiles.gpg]
dotfiles = [
  "f_gpg-agent.conf",
  "f_gpg.conf",
  "f_gpg_scdaemon.conf",
  "f_pam_environment",
]

[profiles.Mirkwood]
include = ["base", "terminal", "email", "media", "sway", "pacman", "gpg"]
dotfiles = ["f_paru.conf", "f_gitconfig", "f_foot.ini"]

[profiles.Moria]
include = ["terminal", "pacman"]
dotfiles = ["f_zprofile"]

[profiles.Gondor]
include = ["terminal", "pacman"]

[profiles.mko-laptop]
include = ["terminal", "media", "gpg"]

[profiles.Edoras]
include = ["terminal", "pacman"]

[profiles.TakamakiPC]
include = ["terminal", "pacman"]

[profiles.localhost]
include = ["terminal"]

[profiles.ViiruJaTeippi]
include = ["terminal"]
