[volumes]
files = {}
config = {}
redis = {}
sonic = {}

[services.firefish]
image = "registry.firefish.dev/firefish/firefish"
container_name = "firefish"
restart = "unless-stopped"
depends_on = ["redis"]
ports = ["3083:3000"]
networks = ["firefish", "proxy", "postgres"]
environment = { NODE_ENV = "production" }
volumes = [
  "files:/firefish/files",
  "config:/firefish/.config:ro",
]

[services.redis]
image = "redis"
container_name = "redis-firefish"
restart = "unless-stopped"
networks = ["firefish"]
volumes = ["redis:/data"]

[services.sonic]
image = "valeriansaliou/sonic:v1.4.0"
container_name = "sonic-firefish"
logging = { driver = "none" }
networks = ["firefish"]
volumes = [
  "sonic:/var/lib/sonic/store",
  "/mnt/Storage/docker/firefish-sonic/config.cfg:/etc/sonic.cfg",
]
env_file = ".env"

[networks.firefish]
internal = true

[networks.proxy]
external = true

[networks.postgres]
external = true
