version: '3'
services:
  home-assistant:
    environment:
      TZ: "Europe/Helsinki"
    container_name: home-assistant
    restart: always
    image: homeassistant/home-assistant
    volumes:
      - /homeautomation-config/home-assistant:/config
    network_mode: host
    depends_on:
      - deconz
      - mosquitto

  deconz:
    container_name: deconz
    image: marthoc/deconz
    restart: always
    environment:
      DECONZ_WEB_PORT: 8083
      DECONZ_WS_PORT: 8084
      DECONZ_VNC_PORT: 5901
      DECONZ_VNC_MODE: 1
      DECONZ_VNC_PASSWORD: "${DECONZ_VNC_PASSWORD}"
      DEBUG_OTAU: 1
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /homeautomation-config/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0

  node-red:
    container_name: node-red
    image: nodered/node-red
    restart: always
    environment:
      TZ: "Europe/Helsinki"
    network_mode: host
    ports:
      - "1880:1880"
    volumes:
      - /homeautomation-config/node-red:/data
    depends_on:
      - home-assistant

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /homeautomation-config/portainer:/data

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    network_mode: host
    volumes:
      - /homeautomation-config/mosquitto:/mosquitto
