volumes:
  config: {}
services:
  searx:
    container_name: searxng
    image: searxng/searxng
    restart: unless-stopped
    networks:
      - default
      - proxy
    volumes:
      - config:/etc/searxng
      - ./branding/logo.png:/usr/local/searxng/searx/static/themes/simple/img/searxng.png:ro
      - ./branding/favicon.png:/usr/local/searxng/searx/static/themes/simple/img/favicon.png:ro
      - ./branding/favicon.svg:/usr/local/searxng/searx/static/themes/simple/img/favicon.svg:ro
    environment:
      - SEARXNG_BASE_URL=https://search.korhonen.cc/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '1'
  redis:
    container_name: redis-searxng
    image: redis:alpine
    command: redis-server --save "" --appendonly "no"
    networks:
      - default
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
networks:
  proxy:
    external: true
