volumes:
  data: {}
  config: {}
  wkd: {}
  korhonen_cc: {}
  nextcloud_config:
    external: true
services:
  caddy:
    image: git.korhonen.cc/functionalhacker/caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
      - 127.0.0.1:2019:2019
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
      - data:/data
      - config:/config
      - wkd:/var/www/wkd
      - korhonen_cc:/var/www/korhonen.cc
      - nextcloud_config:/var/www/nextcloud
      - /var/www/index.korhonen.cc:/var/www/index.korhonen.cc
      - ./templates/:/templates
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
networks:
  proxy:
    external: true
