[volumes]
data = {}
config = {}
wkd = {}
korhonen_cc = {}
index = {}

[volumes.nextcloud_config]
external = true

[services.caddy]
image = "slothcroissant/caddy-cloudflaredns"
container_name = "caddy"
restart = "unless-stopped"
ports = ["80:80", "443:443/tcp", "443:443/udp"]
networks = ["proxy"]
volumes = [
  "./Caddyfile:/etc/caddy/Caddyfile",
  "data:/data",
  "config:/config",
  "wkd:/var/www/wkd",
  "korhonen_cc:/var/www/korhonen.cc",
  "index:/var/www/index.korhonen.cc",
  "nextcloud_config:/var/www/nextcloud",
]
environment = ["CLOUDFLARE_EMAIL", "CLOUDFLARE_API_TOKEN", "ACME_AGREE=true"]

[networks.proxy]
external = true
