volumes:
  data: {}
  config: {}
  wkd: {}
  korhonen_cc: {}
  nextcloud_config:
    external: true
services:
  caddy:
    image: git.korhonen.cc/functionalhacker/caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
      - 127.0.0.1:2019:2019
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
      - data:/data
      - config:/config
      - wkd:/var/www/wkd
      - korhonen_cc:/var/www/korhonen.cc
      - nextcloud_config:/var/www/nextcloud
      - /var/www/index.korhonen.cc:/var/www/index.korhonen.cc
      - /var/cache/pacman/pkg:/var/cache/pacman/pkg
      - ./templates/:/templates
    env_file:
      - .env
    cap_add:
      - NET_ADMIN

  sablier:
    image: sablierapp/sablier
    container_name: sablier
    restart: always
    command:
      - start
      - --provider.name=docker
    networks:
      - proxy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  anubis:
    image: ghcr.io/techarohq/anubis
    container_name: anubis
    restart: unless-stopped
    environment:
      BIND: ":8080"
      TARGET: http://caddy:3001
    networks:
      - proxy
    healthcheck:
      test: ['CMD', 'anubis', '--healthcheck']
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms

networks:
  proxy:
    external: true
