volumes:
  data: {}
  config: {}
  wkd: {}
  korhonen_cc: {}
  crowdsec: {}
  nextcloud_config:
    external: true

services:
  caddy:
    image: git.korhonen.cc/functionalhacker/caddy
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    networks:
      - default
      - proxy
      - monitoring
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
      - data:/data
      - config:/config
      - wkd:/var/www/wkd
      - korhonen_cc:/var/www/korhonen.cc
      - nextcloud_config:/var/www/nextcloud
      - /var/www/index.korhonen.cc:/var/www/index.korhonen.cc
      - /var/cache/pacman/pkg:/var/cache/pacman/pkg
      - ./templates/:/templates
    env_file:
      - .env
    cap_add:
      - NET_ADMIN

  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: always
    environment:
      DB_PASS: ${CROWDSEC_DB_PASS}
    env_file:
      - .env
    networks:
      - default
      - postgres
      - monitoring
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - crowdsec:/etc/crowdsec/
      - ./crowdsec.yaml:/etc/crowdsec/config.yaml.local:ro

  anubis:
    image: ghcr.io/techarohq/anubis
    container_name: anubis
    restart: always
    environment:
      TARGET: http://caddy:3001
    networks:
      - default
      - monitoring
    healthcheck:
      test: ['CMD', 'anubis', '--healthcheck']
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    volumes:
      - /etc/localtime:/etc/localtime:ro

  sablier:
    image: sablierapp/sablier
    container_name: sablier
    restart: always
    command:
      - start
      - --provider.name=docker
      - --server.metrics.enabled=true
    networks:
      - default
      - monitoring
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  proxy:
    external: true
  monitoring:
    external: true
  postgres:
    external: true
