[services.jellyfin]
image = "jellyfin/jellyfin"
container_name = "jellyfin"
environment = ["TZ=Europe/Helsinki"]
ports = ["8096:8096"]
networks = ["proxy", "authentik"]
restart = "unless-stopped"
volumes = [
  "/docker/jellyfin/config:/config",
  "/docker/jellyfin/cache:/cache",
  "/mnt/Storage/Media:/media",
  "/mnt/Storage/Nextcloud/FunctionalHacker/files/Media/Music:/media/Music",
  "/etc/localtime:/etc/localtime:ro",
]
devices = [
  "/dev/dri/renderD128:/dev/dri/renderD128",
  "/dev/dri/card1:/dev/dri/card0",
]

[networks.proxy]
external = true

[networks.authentik]
external = true
