[volumes]
config = {}
cache = {}

[volumes.media]
external = true

[volumes.nextcloud_data]
external = true

[services.jellyfin]
image = "jellyfin/jellyfin"
container_name = "jellyfin"
environment = ["TZ=Europe/Helsinki"]
ports = ["8096:8096"]
networks = ["proxy", "authentik"]
restart = "unless-stopped"
volumes = [
  "config:/config",
  "cache:/cache",
  "media:/media",
  "nextcloud_data:/nextcloud_data",
  "/etc/localtime:/etc/localtime:ro",
]
devices = [
  "/dev/dri/renderD128:/dev/dri/renderD128",
  "/dev/dri/card0:/dev/dri/card0",
]

[networks.proxy]
external = true

[networks.authentik]
external = true
