[services]

[services.freshrss]
image = "linuxserver/freshrss"
container_name = "freshrss"
restart = "unless-stopped"
networks = ["freshrss", "postgres", "proxy"]
environment = ["PUID=1000", "PGID=985", "TZ=Europe/Helsinki"]
volumes = [
  "/docker/freshrss/freshrss:/config",
  "/etc/localtime:/etc/localtime:ro",
]
labels = [
  "traefik.enable=true",
  "traefik.docker.network=proxy",
  "traefik.http.routers.freshrss-redirect.entrypoints=http",
  "traefik.http.routers.freshrss-redirect.rule=Host(`rss.korhonen.cc`)",
  "traefik.http.routers.freshrss-redirect.middlewares=http2https@file",
  "traefik.http.routers.freshrss.entrypoints=https",
  "traefik.http.routers.freshrss.middlewares=secHeaders@file,compress@file",
  "traefik.http.routers.freshrss.rule=Host(`rss.korhonen.cc`)",
  "traefik.http.routers.freshrss.service=freshrss",
  "traefik.http.services.freshrss.loadbalancer.server.port=80",
]

[networks]

[networks.freshrss]
external = false

[networks.postgres]
external = true

[networks.proxy]
external = true
