[services]

[services.freshrss]
image = "linuxserver/freshrss"
container_name = "freshrss"
restart = "unless-stopped"
networks = ["freshrss", "postgres", "proxy"]
environment = ["PUID=1000", "PGID=985", "TZ=Europe/Helsinki"]
depends_on = ["bibliogram"]
volumes = [
  "/docker/freshrss/freshrss:/config",
  "/etc/localtime:/etc/localtime:ro",
]
labels = [
  "traefik.enable=true",
  "traefik.docker.network=proxy",
  "traefik.http.routers.freshrss-redirect.entrypoints=http",
  "traefik.http.routers.freshrss-redirect.rule=Host(`rss.korhonen.cc`)",
  "traefik.http.routers.freshrss-redirect.middlewares=http2https@file",
  "traefik.http.routers.freshrss.entrypoints=https",
  "traefik.http.routers.freshrss.middlewares=secHeaders@file,compress@file",
  "traefik.http.routers.freshrss.rule=Host(`rss.korhonen.cc`)",
  "traefik.http.routers.freshrss.service=freshrss",
  "traefik.http.services.freshrss.loadbalancer.server.port=80",
]

[services.bibliogram]
image = "cloudrac3r/bibliogram"
container_name = "bibliogram"
restart = "unless-stopped"
volumes = [
  "/docker/freshrss/bibliogram/db:/app/db",
  "/docker/freshrss/bibliogram/config.js:/app/config.js",
]
networks = ["freshrss", "proxy"]
labels = [
  "traefik.enable=true",
  "traefik.docker.network=proxy",
  "traefik.http.routers.bibliogram-redirect.entrypoints=http",
  "traefik.http.routers.bibliogram-redirect.rule=Host(`bibliogram.korhonen.cc`)",
  "traefik.http.routers.bibliogram-redirect.middlewares=http2https@file",
  "traefik.http.routers.bibliogram.entrypoints=https",
  "traefik.http.routers.bibliogram.middlewares=secHeaders@file,compress@file",
  "traefik.http.routers.bibliogram.rule=Host(`bibliogram.korhonen.cc`)",
  "traefik.http.routers.bibliogram.service=bibliogram",
  "traefik.http.services.bibliogram.loadbalancer.server.port=10407",
]

[networks]

[networks.freshrss]
external = false

[networks.postgres]
external = true

[networks.proxy]
external = true
