volumes:
  config: {}
services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    restart: unless-stopped
    networks:
      - freshrss
      - postgres
      - proxy
    environment:
      - PUID=1000
      - PGID=985
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
networks:
  freshrss:
    external: false
  postgres:
    external: true
  proxy:
    external: true
