volumes:
  config: {}
  data: {}
services:
  headscale:
    image: headscale/headscale:0
    container_name: headscale
    volumes:
      - config:/etc/headscale
      - data:/var/lib/headscale
    ports:
      - 3478:3478/udp
    command: headscale serve
    restart: unless-stopped
    networks:
      - postgres
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui
    container_name: headscale-ui
    restart: unless-stopped
networks:
  postgres:
    external: true
