services:
  drop:
    image: lscr.io/linuxserver/pairdrop
    container_name: drop
    restart: unless-stopped
    networks:
      - proxy
      - IPV6_LOCALIZE=4
    volumes:
      - /etc/localtime:/etc/localtime:ro
networks:
  proxy:
    external: true
