cache_directory = "/var/cache/flexo/pkg"
connect_timeout = 3000
mirrorlist_fallback_file = "/var/cache/flexo/state/mirrorlist"
mirrorlist_latency_test_results_file = "/var/cache/flexo/state/latency_test_results.json"
listen_ip_address = "0.0.0.0"
port = 7878
mirror_selection_method = "auto"
mirrors_predefined = []
num_versions_retain = 3

[mirrors_auto]

mirrors_status_json_endpoint = "https://archlinux.org/mirrors/status/json/"
mirrors_status_json_endpoint_fallbacks = [
  "https://raw.githubusercontent.com/nroi/archlinux-mirrors-status-fallback/main/mirrorlist.json",
]
mirrors_blacklist = []
https_required = true
ipv4 = true
ipv6 = false
max_score = 2.5
num_mirrors = 8
mirrors_random_or_sort = "sort"
timeout = 350
refresh_latency_tests_after = "8 days"
allowed_countries = []
