version: '3'

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: always
    volumes:
      - /docker/mumble:/etc/mumble
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '64748:64738'
      - '64748:64738/udp'
