volumes:
  config: {}
services:
  mumble:
    container_name: mumble
    image: phlak/mumble
    environment:
      - TZ=Europe/Helsinki
    network_mode: host
    volumes:
      - config:/etc/mumble
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
