[services]

[services.mumble]
container_name = "mumble"
image = "phlak/mumble"
user = "1000:985"
environment = ["TZ=Europe/Helsinki"]
network_mode = "host"
volumes = ["/docker/mumble:/etc/mumble", "/etc/localtime:/etc/localtime:ro"]
restart = "unless-stopped"
