volumes:
  config: {}
services:
  mumble:
    container_name: mumble
    image: phlak/mumble
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/etc/mumble
    restart: unless-stopped
