version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Europe/Helsinki
      - PEERS=4
      - SERVERURL=korhonen.cc
      - SERVERPORT=48574
      - INTERNAL_SUBNET=10.200.200.0/24
    volumes:
      - /docker/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 48574:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
