data_dir = "/var/lib/vector"

[sources.vector_metrics]
type = "internal_metrics"

[sources.docker]
type = "docker_logs"
include_containers = ["caddy", "crowdsec"]

[transforms.docker_parsed]
type = "remap"
inputs = ["docker"]
source = """
parsed, parse_err = parse_json(.message)

# Get only needed fields from Docker metadata
base_fields = {
  "timestamp": .timestamp,
  "container_name": .container_name,
  "compose_project": .label."com.docker.compose.project",
}

# Merge the parsed JSON first, then overwrite/combine with base fields.
# This ensures explicitly selected fields take precedence.
if parse_err == null && is_object(parsed) {
  . = merge!(parsed, base_fields)
}

# Fallback if JSON parsing fails
else {
  . = base_fields
}


# Add summary message for caddy
if .container_name == "caddy" {
  method = string(.request.method) ?? "UNKNOWN"
  uri = string(.request.uri) ?? "/"
  status = to_string(.status) ?? "UNKNOWN"
  .message = join!([method, uri, "-", status], " ")
}

# Remap crowdsec msg to message
else if .container_name == "crowdsec" {
  .message = .msg
}
"""


[sinks.vlogs]
type = "elasticsearch"
inputs = ["docker_parsed"]
endpoints = ["http://victorialogs:9428/insert/elasticsearch/"]
mode = "bulk"
api_version = "v8"
compression = "gzip"

[sinks.vlogs.healthcheck]
enabled = false

[sinks.vlogs.request.headers]
VL-Stream-Fields = "source_type,label.com.docker.compose.service"
VL-Time-Field = "timestamp"
VL-Msg-Field = "message"
AccountID = "0"
ProjectID = "0"

[sinks.victoriametrics]
type = "prometheus_remote_write"
endpoint = "http://victoriametrics:8428/api/v1/write"
inputs = ["vector_metrics"]

[sinks.victoriametrics.healthcheck]
enabled = false
