version: "3.3"

services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    environment:
      - TZ=Europe/Helsinki
      - WORDPRESS_DB_HOST=mariadb-wordpress:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    restart: unless-stopped
    networks:
      - proxy
      - wordpress
    volumes:
      - /docker/wordpress/wordpress:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.wordpress-redirect.entrypoints=http"
      - "traefik.http.routers.wordpress-redirect.rule=Host(`johanna.korhonen.cc`)"
      - "traefik.http.middlewares.http2https.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress-redirect.middlewares=http2https"

      - "traefik.http.routers.wordpress.entrypoints=https"
      - "traefik.http.routers.wordpress.rule=Host(`johanna.korhonen.cc`)"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=http"
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  mariadb-wordpress:
    image: mariadb
    container_name: mariadb-wordpress
    volumes:
      - /docker/wordpress/mariadb:/var/lib/mysql
    restart: always
    networks:
      - wordpress
    environment:
      - MYSQL_ROOT_PASSWORD=oT8Veu3Vre4ohj3E
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

networks:
  proxy:
    external: true
  wordpress:
    external: false
