[volumes.caddy_data]
external = true

[volumes.caddy_config]
external = true

[volumes.caddy_wkd]
external = true

[volumes.homeautomation_hass]
external = true

[services.backup]
image = "offen/docker-volume-backup:v2"
container_name = "volume-backup"
environment = [
  "AWS_ENDPOINT",
  "AWS_S3_BUCKET_NAME",
  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "GPG_PASSPHRASE",
  "EMAIL_SMTP_HOST",
  "EMAIL_SMTP_PASSWORD",
  "EMAIL_SMTP_USERNAME",
  "EMAIL_SMTP_PORT",
  "BACKUP_COMPRESSION=zst",
  "BACKUP_RETENTION_DAYS=7",
]
volumes = [
  "/var/run/docker.sock:/var/run/docker.sock:ro",
  "/etc/localtime:/etc/localtime:ro",
  "caddy_data:/backup/caddy_data:ro",
  "caddy_config:/backup/caddy_config:ro",
  "caddy_wkd:/backup/caddy_wkd:ro",
  "homeautomation_hass:/backup/homeautomation_hass:ro",
]
