services:
  scanservjs:
    container_name: scanservjs
    image: sbs20/scanservjs
    restart: unless-stopped
    networks:
      - proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - 'SANED_NET_HOSTS=host.docker.internal'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus
      - ./dll.conf:/etc/sane.d/dll.conf

networks:
  proxy:
    external: true
