volumes:
  config: {}
  dnsmasq: {}
services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8069:80/tcp
    networks:
      - proxy
    volumes:
      - config:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      TZ: Europe/Helsinki
      WEBPASSWORD: ${WEBPASSWORD}
networks:
  proxy:
    external: true
