version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8069:80/tcp"
      - "8070:443/tcp"
    environment:
      TZ: "Europe/Helsinki"
      WEBPASSWORD: "${WEBPASSWORD}"
    volumes:
      - "/docker/pihole/pihole:/etc/pihole/"
      - "/docker/pihole/dnsmasq:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pihole/docker-pihole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
