[services]

[services.nginx]
image = "nginx"
container_name = "korhonen.cc"
volumes = ["/docker/korhonen.cc:/korhonen.cc:ro", "./nginx.conf:/etc/nginx/conf.d/default.conf"]
networks = ["proxy"]
restart = "unless-stopped"
labels = [
  "traefik.enable=true",
  "traefik.http.routers.korhonen-redirect.entrypoints=http",
  "traefik.http.routers.korhonen-redirect.rule=Host(`korhonen.cc`)",
  "traefik.http.routers.korhonen-redirect.middlewares=http2https@file",
  "traefik.http.routers.korhonen.entrypoints=https",
  "traefik.http.routers.korhonen.rule=Host(`korhonen.cc`)",
  "traefik.http.routers.korhonen.service=korhonen",
  "traefik.docker.network=proxy",
  "traefik.http.services.korhonen.loadbalancer.server.port=80",
]

[networks]

[networks.proxy]
external = true
