volumes:
  config: {}

services:
  tvheadend:
    image: ghcr.io/tvheadend/tvheadend
    container_name: tvheadend
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/var/lib/tvheadend
      - /mnt/Storage/Media/PVR:/var/lib/tvheadend/recordings
    ports:
      - 9981:9981
      - 9982:9982
    networks:
      - proxy
    healthcheck:
      test: wget -O - -q 'http://localhost:9981/ping' | grep -q 'PONG'
    # devices:
    #   - /dev/dvb:/dev/dvb

networks:
  proxy:
    external: true
