[services.tvheadend]
image = "linuxserver/tvheadend"
container_name = "tvheadend"
environment = ["TZ=Europe/Helsinki", "PUID=1000", "PGID=985"]
volumes = [
  "/docker/tvheadend:/config",
  "/mnt/Storage/Media/PVR:/recordings",
  "/mnt/Storage/picons:/picons",
  "/etc/localtime:/etc/localtime:ro",
]
ports = ["9981:9981", "9982:9982"]
devices = ["/dev/dvb:/dev/dvb"]
restart = "unless-stopped"
networks = ["proxy"]

[networks.proxy]
external = true
