version: "2"
services:
  tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    user: "1000:985"
    environment:
      - TZ=Europe/Helsinki
      - PUID=1000
      - PGID=985
    volumes:
      - /docker/tvheadend:/config
      - /mnt/Storage/Media/PVR:/recordings
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dri:/dev/dri #hardware acceleration
      - /dev/dvb:/dev/dvb #tuner card
    restart: always
