volumes:
  config: {}
  pvr:
    external: true
  picons:
    external: true

services:
  tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=985
      - RUN_OPTS=--ipv6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - pvr:/recordings
      - picons:/picons
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dvb:/dev/dvb
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
