volumes:
  config: {}
  picons: {}
services:
  tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=985
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - picons:/picons
      - /mnt/Storage/Media/PVR:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dvb:/dev/dvb
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
