volumes:
  config: {}
services:
  searx:
    container_name: searx
    image: searxng/searxng
    restart: unless-stopped
    networks:
      - searx
      - proxy
    volumes:
      - config:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=https://search.korhonen.cc/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
  redis:
    container_name: redis-searx
    image: redis:alpine
    command: redis-server --save "" --appendonly "no"
    networks:
      - searx
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
networks:
  searx:
    ipam:
      driver: default
  proxy:
    external: true
