[volumes]
data = {}
runner = {}

[services.forgejo]
image = "git.korhonen.cc/functionalhacker/forgejo-asciidoc"
container_name = "forgejo"
environment = ["TZ=Europe/Helsinki", "USER_UID=1000", "USER_GID=1000"]
restart = "unless-stopped"
networks = ["postgres", "proxy"]
ports = ["22:22"]
volumes = ["data:/data", "/etc/localtime:/etc/localtime:ro"]

[services.runner]
image = "code.forgejo.org/forgejo/runner:3.4.1"
container_name = "forgejo-runner"
user = "root:root"
volumes = [
  "runner:/data",
  "./runner.yaml:/data/config.yaml",
  "/var/run/docker.sock:/var/run/docker.sock",
  "/etc/localtime:/etc/localtime:ro",
]
environment = ["SOCKFILE=/var/run/docker.sock"]
restart = "unless-stopped"
command = "forgejo-runner daemon -c /data/config.yaml"

[networks.postgres]
external = true

[networks.proxy]
external = true
