[volumes]
data = {}

[services.forgejo]
image = "git.korhonen.cc/functionalhacker/forgejo-asciidoc"
container_name = "forgejo"
environment = ["TZ=Europe/Helsinki"]
restart = "unless-stopped"
networks = ["postgres", "proxy"]
ports = ["22:22"]
volumes = ["data:/data", "/etc/localtime:/etc/localtime:ro"]

[networks.postgres]
external = true

[networks.proxy]
external = true
