log:
  level: info
  job_level: info
runner:
  file: .runner
  capacity: 1
  envs:
  env_file: .env
  timeout: 3h
  shutdown_timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  report_interval: 1s
  labels:
    - 'docker:docker://git.korhonen.cc/functionalhacker/ubuntu-act:latest'

cache:
  enabled: true
  dir: ''
  host: ''
  proxy_port: 0
  actions_cache_url_override: ''
  external_server: ''
  secret: ''
container:
  network: ''
  enable_ipv6: false
  privileged: false
  options:
  workdir_parent:
  valid_volumes:
    - 'caddy_korhonen_cc'
  docker_host: 'automount'
  force_pull: false
  force_rebuild: false

host:
  workdir_parent:
