[notmuch]
source = notmuch://~/.local/share/mail/
maildir-store = ~/.local/share/mail/
outgoing = /usr/bin/sendmail -a marko
copy-to = marko/Sent
query-map = ~/.config/aerc/notmuch.qmap
default = Inbox
folders-sort = Inbox
from = Marko Korhonen <marko@korhonen.cc>

[marko]
source = maildir://~/.local/share/mail/marko
outgoing = /usr/bin/sendmail -a marko
from = Marko Korhonen <marko@korhonen.cc>
default = Inbox
folders-sort = Inbox
copy-to = Sent

[functionalhacker]
source = maildir://~/.local/share/mail/functionalhacker
outgoing = /usr/bin/sendmail -a functionalhacker
from = Marko Korhonen <functionalhacker@korhonen.cc>
default = Inbox
folders-sort = Inbox
copy-to = Sent


[admin]
source = maildir://~/.local/share/mail/admin
outgoing = /usr/bin/sendmail -a admin
from = Korhonen Admin <admin@korhonen.cc>
default = Inbox
folders-sort = Inbox
copy-to = Sent
