volumes:
  nextcloud_config:
    external: true
  nextcloud_data:
    external: true
  nextcloud_app:
    external: true

services:
  nextcloud:
    image: nextcloud:fpm-alpine
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - default
      - postgres
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud_app:/var/www/html
      - nextcloud_config:/config
      - nextcloud_data:/data
    environment:
      - NEXTCLOUD_CONFIG_DIR=/config
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.korhonen.cc
      - OVERWRITEHOST=cloud.korhonen.cc
      - OVERWRITEPROTOCOL=https
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=123
      - TRUSTED_PROXIES=caddy
    depends_on:
      - redis
    labels:
      ofelia.enabled: true
      ofelia.job-exec.nextcloud.schedule: 0 */5 * * * *
      ofelia.job-exec.nextcloud.command: php /var/www/html/cron.php
      ofelia.job-exec.nextcloud.user: www-data
      ofelia.job-exec.nextcloud.smtp-host: ${SMTP_HOST}
      ofelia.job-exec.nextcloud.smtp-port: ${SMTP_PORT}
      ofelia.job-exec.nextcloud.smtp-user: ${SMTP_USER}
      ofelia.job-exec.nextcloud.smtp-password: ${SMTP_PASSWORD}
      ofelia.job-exec.nextcloud.email-to: ${EMAIL_TO}
      ofelia.job-exec.nextcloud.email-from: ${EMAIL_FROM}
      ofelia.job-exec.nextcloud.mail-only-on-error: true

  redis:
    image: redis:alpine
    container_name: redis-nextcloud
    networks:
      - default
    restart: unless-stopped
    command: redis-server --requirepass 123

networks:
  postgres:
    external: true
  proxy:
    external: true
