volumes:
  data: {}
  keys: {}

services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger
    container_name: lubelogger
    restart: no
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/App/data
      - keys:/root/.aspnet/DataProtection-Keys
    env_file: .env
    networks:
      - proxy
      - postgres
    labels:
      - sablier.enable=true
      - sablier.group=lubelogger

networks:
  postgres:
    external: true
  proxy:
    external: true
