volumes:
  data: {}
  keys: {}

services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:latest
    container_name: lubelogger
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/App/data
      - keys:/root/.aspnet/DataProtection-Keys
    env_file:
      - .env
    networks:
      - proxy
      - postgres

networks:
  postgres:
    external: true
  proxy:
    external: true
