services:
  tftp:
    container_name: tftp
    image: pghalliday/tftp
    restart: unless-stopped
    ports:
      - 69:69/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/tftp:/var/tftpboot
