[experimental]
http3 = true

[api]
dashboard = true

[entryPoints.http]
address = ":80"

[entryPoints.https]
address = ":443"

[entryPoints.https.http3]

[entryPoints.https.http.tls]
options = "default"
certResolver = "letsEncrypt"

[[entryPoints.https.http.tls.domains]]
main = "korhonen.cc"
sans = ["*.korhonen.cc"]

[certificatesResolvers.letsEncrypt.acme]
email = "admin@korhonen.cc"
storage = "acme.json"

[certificatesResolvers.letsEncrypt.acme.dnsChallenge]
provider = "cloudflare"

[accessLog]
filePath = "/var/log/access.log"

[accessLog.filters]
statusCodes = ["400-499"]

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[providers.file]
filename = "/dynamic.toml"
