[services.woodpecker]
image = "woodpeckerci/woodpecker-server"
container_name = "woodpecker"
restart = "unless-stopped"
volumes = ["/docker/woodpecker/:/var/lib/woodpecker/"]
env_file = [".env"]
environment = [
  "WOODPECKER_OPEN=true",
  "WOODPECKER_GITEA=true",
  "WOODPECKER_GITEA_URL=https://git.korhonen.cc",
  "WOODPECKER_GITEA_CLIENT",
  "WOODPECKER_GITEA_SECRET",
  "WOODPECKER_AGENT_SECRET",
  "WOODPECKER_HOST=https://ci.korhonen.cc",
  "WOODPECKER_ADMIN=FunctionalHacker",
]
networks = ["proxy", "default"]

[services.woodpecker-agent]
image = "woodpeckerci/woodpecker-agent"
container_name = "woodpecker-agent"
command = "agent"
restart = "unless-stopped"
depends_on = ["woodpecker"]
volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
env_file = [".env"]
environment = [
  "WOODPECKER_SERVER=woodpecker:9000",
  "WOODPECKER_AGENT_SECRET",
]

[networks.proxy]
external = true
