[services.opentogethertube]
image = "dyc3/opentogethertube"
container_name = "opentogethertube"
restart = "unless-stopped"
environment = [
  "PORT=8080",
  "REDIS_HOST=redis",
  "REDIS_PORT=6379",
  "FFPROBE_PATH=/usr/bin/ffprobe",
  "DB_MODE=postgres",
  "POSTGRES_USER=opentogethertube",
  "POSTGRES_DB=opentogethertube",
  "POSTGRES_HOST=postgres",
  "POSTGRES_PASSWORD",
  "DOCKER=1",
  "OTT_HOSTNAME=ott.korhonen.cc",
  "YOUTUBE_API_KEY",
  "OPENTOGETHERTUBE_API_KEY",
  "SESSION_SECRET",
]
ports = ["8080:8080", "3002:3002"]
networks = ["default", "postgres", "proxy"]
depends_on = ["redis"]
volumes = ["./production.toml:/app/env/production.toml"]

[services.redis]
container_name = "redis-opentogethertube"
image = "redis:alpine"
restart = "unless-stopped"

[services.redis.healthcheck]
test = "redis-cli ping"

[networks.postgres]
external = true

[networks.proxy]
external = true
