#!/bin/bash

source $DOTREPO/secrets/env

cat <<SECRET > $DOTREPO/secrets/secrets
export PASS_LIBREFM="$PASS_LIBREFM"
export PASS_MUSICBRAINZ="$PASS_MUSICBRAINZ"
export PASS_LISTENBRAINZ="$PASS_LISTENBRAINZ"
export PASS_MUSPY="$PASS_MUSPY"
export PASS_ARIA2="$PASS_ARIA2"
export PASS_MPD="$PASS_MPD"
export PASS_MPD_ADMIN="$PASS_MPD_ADMIN"
export PASS_IPMI="$PASS_IPMI"
export PASS_MQTT="$PASS_MQTT"

export ME_FULLNAME="$ME_FULLNAME"
export ME_ADDRESS="$ME_ADDRESS"
export ME_PHONE="$ME_PHONE"

export WIREGUARD_MIRKWOOD_PRIVKEY="$WIREGUARD_MIRKWOOD_PRIVKEY"
export WIREGUARD_MIRKWOOD_PUBKEY="$WIREGUARD_MIRKWOOD_PUBKEY"
export WIREGUARD_MIRKWOOD_PSK="$WIREGUARD_MIRKWOOD_PSK"

export WIREGUARD_MORIA_PRIVKEY="$WIREGUARD_MORIA_PRIVKEY"
export WIREGUARD_MORIA_PUBKEY="$WIREGUARD_MORIA_PUBKEY"
SECRET
